services:
  server:
    build: .
    container_name: team1-server
    ports:
      - "6000:3000"
    restart: unless-stopped
    volumes:
      - ./firebase-service.json:/app/firebase-service.json
      - ./.env:/app/.env
