services:
  server:
    build: .
    container_name: team1-server
    ports:
      - "6000:3000"
    restart: unless-stopped
    volumes:
      - ./.env:/usr/src/app/.env
      - ./firebase-service.json:/usr/src/app/firebase-service.json
      - ./confidential-data:/usr/src/app/confidential-data
