name: Deploy NodeJS App (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from GitHub secret
        run: echo "${{ secrets.PROD_ENV_FILE }}" > .env

      - name: Create Firebase JSON file from secret
        run: |
          echo "${{ secrets.FIREBASE_SERVICE }}" | base64 --decode > firebase-service.json

      - name: Decode certs
        run: |
          echo "${{ secrets.NODE_PRIVATE_KEY_B64 }}" | base64 --decode > confidential-data/node.key
          echo "${{ secrets.NODE_CRT_B64 }}" | base64 --decode > confidential-data/node.crt
          echo "${{ secrets.CA_CRT_B64 }}" | base64 --decode > confidential-data/ca.crt

      - name: Pull latest changes
        run: git pull origin main

      - name: Set container name
        run: |

          if [ -z "${{ secrets.CONTAINER_NAME }}" ]; then
            echo "ERROR: El secreto CONTAINER_NAME no estÃ¡ definido"
            exit 1
          fi
          echo "CONTAINER_NAME=${{ secrets.CONTAINER_NAME }}" >> $GITHUB_ENV

      - name: Build and restart Docker container
        run: |
          cd $GITHUB_WORKSPACE


          docker rm -f $CONTAINER_NAME || true


          docker compose -f docker-compose.yml up -d --build server

      - name: Clean up
        run: echo "Deployment for $CONTAINER_NAME complete."
